services:
  unifi-backup-docker-tool:
    container_name: unifi-backup-docker-tool
    image: ghcr.io/reply-nick/unifi-backup-docker-tool:latest
    env_file: .env
    environment:
      - TZ=America/Chicago
    volumes:
      - ./backups:/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import time, os; exit(0) if os.path.getmtime('/var/log/unifi-backup.log') > time.time() - 3600 else exit(1)\""]
      interval: 5m
      timeout: 10s
      retries: 1
      start_period: 2m
